### ISSUE TITLE
Bug: Colobar is not generated

### ISSUE THREAD

**Issue by josuemtzmo** [blendernc/blendernc#104]
If the dataset doesn't contain units, BlenderNC crashes before generating colorbar.

```
location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "/Users/josue/Library/Application Support/Blender/2.93/scripts/addons/blendernc/operators.py", line 247, in execute
    update_colormap_interface(context, self.node, self.node_group)
  File "/Users/josue/Library/Application Support/Blender/2.93/scripts/addons/blendernc/python_functions.py", line 504, in update_colormap_interface
    unit_obj = unit_objs[0]
IndexError: list index out of range
```

**Comment by josuemtzmo** [comment]
#102  Fixes this issue
