### ISSUE TITLE
Error when trying to install BlenderNC 0.4.9

### ISSUE THREAD

**Issue by StephanSiemen** [blendernc/blendernc#153]
OS: macOS Big Sur (intel)
Blender Version: 2.93.3
BlenderNC Version: 0.4.9

When installing latest zip file get the following error. Files are copied into ~/Library/Application\ Support/Blender/2.93/scripts/addons/, but Blender does not see add-on in Preferences :-(

Thanks
Stephan

AST error parsing bl_info for: '/Users/stephan/Library/Application Support/Blender/2.93/scripts/addons/blendernc/__init__.py'
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.93/scripts/modules/addon_utils.py", line 137, in fake_module
    mod.bl_info = ast.literal_eval(body.value)
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/ast.py", line 105, in literal_eval
    return _convert(node_or_string)
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/ast.py", line 94, in _convert
    return dict(zip(map(_convert, node.keys),
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/ast.py", line 104, in _convert
    return _convert_signed_num(node)
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/ast.py", line 78, in _convert_signed_num
    return _convert_num(node)
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/ast.py", line 69, in _convert_num
    _raise_malformed_node(node)
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/ast.py", line 66, in _raise_malformed_node
    raise ValueError(f'malformed node or string: {node!r}')
ValueError: malformed node or string: <ast.Call object at 0x1320d46a0>
Modules Installed () from '/Users/stephan/Downloads/blendernc.zip' into '/Users/stephan/Library/Application Support/Blender/2.93/scripts/addons'

**Comment by josuemtzmo** [comment]
Hello @StephanSiemen, thanks for reporting.  This issue is related to the automatization of releases (more info at #155). I've fixed this by removing the automatic release from the `bl_info` variable in in the `__init__.py`.

**Comment by josuemtzmo** [comment]
I've tested it, and now it's fixed.

**Comment by StephanSiemen** [comment]
Can also confirm that is works now. Thanks @josuemtzmo
