### ISSUE TITLE
Just installed, can point it to a nc file but no variables show up. python packages seem in order

### ISSUE THREAD

**Issue by g-randazzo** [blendernc/blendernc#194]
**Here is the output from my terminal when I loaded in the nc file:** 

(base) gregoriorandazzo@pop-os:~/Desktop/blender-4.0.2-linux-x64$ ./blender
Read prefs: "/home/gregoriorandazzo/.config/blender/4.0/config/userpref.blend"
blendernc addon: Verbose is enabled
blendernc addon: Read in JSON settings from file
Registering to Change Defaults
Attempting to load ('/home/gregoriorandazzo/era5_soil_type_2000_monthly', '.nc') format files
Traceback (most recent call last):
  File "/home/gregoriorandazzo/.config/blender/4.0/scripts/addons/blendernc/operators.py", line 78, in execute
    node.blendernc_dict[unique_identifier] = bNCEngine.check_files_datacube(
  File "/home/gregoriorandazzo/.config/blender/4.0/scripts/addons/blendernc/python_functions.py", line 420, in check_files_datacube
    self.check_datacube()
  File "/home/gregoriorandazzo/.config/blender/4.0/scripts/addons/blendernc/python_functions.py", line 436, in check_datacube
    self.load_datacube()
  File "/home/gregoriorandazzo/.config/blender/4.0/scripts/addons/blendernc/python_functions.py", line 453, in load_datacube
    self.dataset = xarray.open_mfdataset(
  File "/home/gregoriorandazzo/.local/lib/python3.10/site-packages/xarray/backends/api.py", line 1056, in open_mfdataset
    datasets = [open_(p, **open_kwargs) for p in paths]
  File "/home/gregoriorandazzo/.local/lib/python3.10/site-packages/xarray/backends/api.py", line 1056, in <listcomp>
    datasets = [open_(p, **open_kwargs) for p in paths]
  File "/home/gregoriorandazzo/.local/lib/python3.10/site-packages/xarray/backends/api.py", line 579, in open_dataset
    ds = _dataset_from_backend_dataset(
  File "/home/gregoriorandazzo/.local/lib/python3.10/site-packages/xarray/backends/api.py", line 372, in _dataset_from_backend_dataset
    ds = _chunk_ds(
  File "/home/gregoriorandazzo/.local/lib/python3.10/site-packages/xarray/backends/api.py", line 337, in _chunk_ds
    variables[name] = _maybe_chunk(
  File "/home/gregoriorandazzo/.local/lib/python3.10/site-packages/xarray/core/dataset.py", line 299, in _maybe_chunk
    chunked_array_type = guess_chunkmanager(
  File "/home/gregoriorandazzo/.local/lib/python3.10/site-packages/xarray/namedarray/parallelcompat.py", line 119, in guess_chunkmanager
    raise TypeError(
TypeError: manager must be a string or instance of ChunkManagerEntrypoint, but received type <class 'xarray.core.daskmanager.DaskManager'>
Error: Python: Traceback (most recent call last):
  File "/home/gregoriorandazzo/.config/blender/4.0/scripts/addons/blendernc/python_functions.py", line 436, in check_datacube
    self.load_datacube()
  File "/home/gregoriorandazzo/.config/blender/4.0/scripts/addons/blendernc/python_functions.py", line 453, in load_datacube
    self.dataset = xarray.open_mfdataset(
  File "/home/gregoriorandazzo/.local/lib/python3.10/site-packages/xarray/backends/api.py", line 1056, in open_mfdataset
    datasets = [open_(p, **open_kwargs) for p in paths]
  File "/home/gregoriorandazzo/.local/lib/python3.10/site-packages/xarray/backends/api.py", line 1056, in <listcomp>
    datasets = [open_(p, **open_kwargs) for p in paths]
  File "/home/gregoriorandazzo/.local/lib/python3.10/site-packages/xarray/backends/api.py", line 579, in open_dataset
    ds = _dataset_from_backend_dataset(
  File "/home/gregoriorandazzo/.local/lib/python3.10/site-packages/xarray/backends/api.py", line 372, in _dataset_from_backeTraceback (most recent call last):
  File "/home/gregoriorandazzo/.config/blender/4.0/scripts/addons/blendernc/decorators.py", line 28, in wrapper_update
    update = cls.shouldIupdate(node)
  File "/home/gregoriorandazzo/.config/blender/4.0/scripts/addons/blendernc/decorators.py", line 52, in shouldIupdate
    update = cls.input_connections(node)
  File "/home/gregoriorandazzo/.config/blender/4.0/scripts/addons/blendernc/decorators.py", line 141, in input_connections
    return cls.get_dataset(node)
  File "/home/gregoriorandazzo/.config/blender/4.0/scripts/addons/blendernc/decorators.py", line 157, in get_dataset
    return cls.select_var_dataset(node)
  File "/home/gregoriorandazzo/.config/blender/4.0/scripts/addons/blendernc/decorators.py", line 270, in select_var_dataset
    bpy.ops.blendernc.datacubeload(
  File "/home/gregoriorandazzo/Desktop/blender-4.0.2-linux-x64/4.0/scripts/modules/bpy/ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/home/gregoriorandazzo/.config/blender/4.0/scripts/addons/blendernc/python_functions.py", line 436, in check_datacube
    self.load_datacube()
  File "/home/gregoriorandazzo/.config/blender/4.0/scripts/addons/blendernc/python_functions.py", line 453, in load_datacube
    self.dataset = xarray.open_mfdataset(
  File "/home/gregoriorandazzo/.local/lib/python3.10/site-packages/xarray/backends/api.py", line 1056, in open_mfdataset
    datasets = [open_(p, **open_kwargs) for p in paths]
  File "/home/gregoriorandazzo/.local/lib/python3.10/site-packages/xarray/backends/api.py", line 1056, in <listcomp>
    datasets = [open_(p, **open_kwargs) for p in paths]
  File "/home/gregoriorandazzo/.local/lib/python3.10/site-packages/xarray/backends/api.py", line 579, in open_dataset
    ds = _dataset_from_backend_dataset(
  File "/home/gregoriorandazzo/.local/lib/python3.10/site-packages/xarray/backends/api.py", line 372, in _dataset_from_backend_dataset
    ds = _chunk_ds(
  File "/home/gregoriorandazzo/.local/lib/python3.10/site-packages/xarray/backends/api.py", line 337, in _chunk_ds
    variables[name] = _maybe_chunk(
  File "/home/gregoriorandazzo/.local/lib/python3.10/site-packages/xarray/core/dataset.py", line 299, in _maybe_chunk
    chunked_array_type = guess_chunkmanager(
  File "/home/gregoriorandazzo/.local/lib/python3.10/site-packages/xarray/namedarray/parallelcompat.py", line 119, in guess_chunkmanager
    raise TypeError(
TypeError: manager must be a string or instance of ChunkManagerEntrypoint, but received type <class 'xarray.core.daskmanager.DaskManager'>
Location: /home/gregoriorandazzo/Desktop/blender-4.0.2-linux-x64/4.0/scripts/modules/bpy/ops.py:109

... truncatedAttempting to load ('/home/gregoriorandazzo/era5_soil_type_2000_monthly', '.nc') format files
Traceback (most recent call last):
  File "/home/gregoriorandazzo/.config/blender/4.0/scripts/addons/blendernc/operators.py", line 78, in execute
    node.blendernc_dict[unique_identifier] = bNCEngine.check_files_datacube(
  File "/home/gregoriorandazzo/.config/blender/4.0/scripts/addons/blendernc/python_functions.py", line 420, in check_files_datacube
    self.check_datacube()
  File "/home/gregoriorandazzo/.config/blender/4.0/scripts/addons/blendernc/python_functions.py", line 436, in check_datacube
    self.load_datacube()
  File "/home/gregoriorandazzo/.config/blender/4.0/scripts/addons/blendernc/python_functions.py", line 453, in load_datacube
    self.dataset = xarray.open_mfdataset(
  File "/home/gregoriorandazzo/.local/lib/python3.10/site-packages/xarray/backends/api.py", line 1056, in open_mfdataset
    datasets = [open_(p, **open_kwargs) for p in paths]
  File "/home/gregoriorandazzo/.local/lib/python3.10/site-packages/xarray/backends/api.py", line 1056, in <listcomp>
    datasets = [open_(p, **open_kwargs) for p in paths]
  File "/home/gregoriorandazzo/.local/lib/python3.10/site-packages/xarray/backends/api.py", line 579, in open_dataset
    ds = _dataset_from_backend_dataset(
  File "/home/gregoriorandazzo/.local/lib/python3.10/site-packages/xarray/backends/api.py", line 372, in _dataset_from_backend_dataset
    ds = _chunk_ds(
  File "/home/gregoriorandazzo/.local/lib/python3.10/site-packages/xarray/backends/api.py", line 337, in _chunk_ds
    variables[name] = _maybe_chunk(
  File "/home/gregoriorandazzo/.local/lib/python3.10/site-packages/xarray/core/dataset.py", line 299, in _maybe_chunk
    chunked_array_type = guess_chunkmanager(
  File "/home/gregoriorandazzo/.local/lib/python3.10/site-packages/xarray/namedarray/parallelcompat.py", line 119, in guess_chunkmanager
    raise TypeError(
TypeError: manager must be a string or instance of ChunkManagerEntrypoint, but received type <class 'xarray.core.daskmanager.DaskManager'>
Error: Python: Traceback (most recent call last):
  File "/home/gregoriorandazzo/.config/blender/4.0/scripts/addons/blendernc/python_functions.py", line 436, in check_datacube
    self.load_datacube()
  File "/home/gregoriorandazzo/.config/blender/4.0/scripts/addons/blendernc/python_functions.py", line 453, in load_datacube
    self.dataset = xarray.open_mfdataset(
  File "/home/gregoriorandazzo/.local/lib/python3.10/site-packages/xarray/backends/api.py", line 1056, in open_mfdataset
    datasets = [open_(p, **open_kwargs) for p in paths]
  File "/home/gregoriorandazzo/.local/lib/python3.10/site-packages/xarray/backends/api.py", line 1056, in <listcomp>
    datasets = [open_(p, **open_kwargs) for p in paths]
  File "/home/gregoriorandazzo/.local/lib/python3.10/site-packages/xarray/backends/api.py", line 579, in open_dataset
    ds = _dataset_from_backend_dataset(
  File "/home/gregoriorandazzo/.local/lib/python3.10/site-packages/xarray/backends/api.py", line 372, in _dataset_from_backeTraceback (most recent call last):
  File "/home/gregoriorandazzo/.config/blender/4.0/scripts/addons/blendernc/operators.py", line 130, in execute
    datacube.update()
  File "/home/gregoriorandazzo/.config/blender/4.0/scripts/addons/blendernc/decorators.py", line 28, in wrapper_update
    update = cls.shouldIupdate(node)
  File "/home/gregoriorandazzo/.config/blender/4.0/scripts/addons/blendernc/decorators.py", line 52, in shouldIupdate
    update = cls.input_connections(node)
  File "/home/gregoriorandazzo/.config/blender/4.0/scripts/addons/blendernc/decorators.py", line 141, in input_connections
    return cls.get_dataset(node)
  File "/home/gregoriorandazzo/.config/blender/4.0/scripts/addons/blendernc/decorators.py", line 157, in get_dataset
    return cls.select_var_dataset(node)
  File "/home/gregoriorandazzo/.config/blender/4.0/scripts/addons/blendernc/decorators.py", line 270, in select_var_dataset
    bpy.ops.blendernc.datacubeload(
  File "/home/gregoriorandazzo/Desktop/blender-4.0.2-linux-x64/4.0/scripts/modules/bpy/ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/home/gregoriorandazzo/.config/blender/4.0/scripts/addons/blendernc/python_functions.py", line 436, in check_datacube
    self.load_datacube()
  File "/home/gregoriorandazzo/.config/blender/4.0/scripts/addons/blendernc/python_functions.py", line 453, in load_datacube
    self.dataset = xarray.open_mfdataset(
  File "/home/gregoriorandazzo/.local/lib/python3.10/site-packages/xarray/backends/api.py", line 1056, in open_mfdataset
    datasets = [open_(p, **open_kwargs) for p in paths]
  File "/home/gregoriorandazzo/.local/lib/python3.10/site-packages/xarray/backends/api.py", line 1056, in <listcomp>
    datasets = [open_(p, **open_kwargs) for p in paths]
  File "/home/gregoriorandazzo/.local/lib/python3.10/site-packages/xarray/backends/api.py", line 579, in open_dataset
    ds = _dataset_from_backend_dataset(
  File "/home/gregoriorandazzo/.local/lib/python3.10/site-packages/xarray/backends/api.py", line 372, in _dataset_from_backend_dataset
    ds = _chunk_ds(
  File "/home/gregoriorandazzo/.local/lib/python3.10/site-packages/xarray/backends/api.py", line 337, in _chunk_ds
    variables[name] = _maybe_chunk(
  File "/home/gregoriorandazzo/.local/lib/python3.10/site-packages/xarray/core/dataset.py", line 299, in _maybe_chunk
    chunked_array_type = guess_chunkmanager(
  File "/home/gregoriorandazzo/.local/lib/python3.10/site-packages/xarray/namedarray/parallelcompat.py", line 119, in guess_chunkmanager
    raise TypeError(
TypeError: manager must be a string or instance of ChunkManagerEntrypoint, but received type <class 'xarray.core.daskmanager.DaskManager'>
Location: /home/gregoriorandazzo/Desktop/blender-4.0.2-linux-x64/4.0/scripts/modules/bpy/ops.py:109

... truncatedError: Python: Traceback (most recent call last):
  File "/home/gregoriorandazzo/.config/blender/4.0/scripts/addons/blendernc/operators.py", line 130, in execute
    datacube.update()
  File "/home/gregoriorandazzo/.config/blender/4.0/scripts/addons/blendernc/decorators.py", line 28, in wrapper_update
    update = cls.shouldIupdate(node)
  File "/home/gregoriorandazzo/.config/blender/4.0/scripts/addons/blendernc/decorators.py", line 52, in shouldIupdate
    update = cls.input_connections(node)
  File "/home/gregoriorandazzo/.config/blender/4.0/scripts/addons/blendernc/decorators.py", line 141, in input_connections
    return cls.get_dataset(node)
  File "/home/gregoriorandazzo/.config/blender/4.0/scripts/addons/blendernc/decorators.py", line 157, in get_dataset
    return cls.select_var_dataset(node)
  File "/home/gregoriorandazzo/.config/blender/4.0/scripts/addons/blendernc/decorators.py", line 270, in select_var_dataset
    bpy.ops.blendernc.datacubeload(
  File "/home/gregoriorandazTraceback (most recent call last):
  File "/home/gregoriorandazzo/.config/blender/4.0/scripts/addons/blendernc/core/update_ui.py", line 352, in update_file_vars
    bpy.ops.blendernc.var(file_path=bpy.context.scene.blendernc_file)
  File "/home/gregoriorandazzo/Desktop/blender-4.0.2-linux-x64/4.0/scripts/modules/bpy/ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/home/gregoriorandazzo/.config/blender/4.0/scripts/addons/blendernc/operators.py", line 130, in execute
    datacube.update()
  File "/home/gregoriorandazzo/.config/blender/4.0/scripts/addons/blendernc/decorators.py", line 28, in wrapper_update
    update = cls.shouldIupdate(node)
  File "/home/gregoriorandazzo/.config/blender/4.0/scripts/addons/blendernc/decorators.py", line 52, in shouldIupdate
    update = cls.input_connections(node)
  File "/home/gregoriorandazzo/.config/blender/4.0/scripts/addons/blendernc/decorators.py", line 141, in input_connections
    return cls.get_dataset(node)
  File "/home/gregoriorandazzo/.config/blender/4.0/scripts/addons/blendernc/decorators.py", line 157, in get_dataset
    return cls.select_var_dataset(node)
  File "/home/gregoriorandazzo/.config/blender/4.0/scripts/addons/blendernc/decorators.py", line 270, in select_var_dataset
    bpy.ops.blendernc.datacubeload(
  File "/home/gregoriorandazzo/Desktop/blender-4.0.2-linux-x64/4.0/scripts/modules/bpy/ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/home/gregoriorandazzo/.config/blender/4.0/scripts/addons/blendernc/python_functions.py", line 436, in check_datacube
    self.load_datacube()
  File "/home/gregoriorandazzo/.config/blender/4.0/scripts/addons/blendernc/python_functions.py", line 453, in load_datacube
    self.dataset = xarray.open_mfdataset(
  File "/home/gregoriorandazzo/.local/lib/python3.10/site-packages/xarray/backends/api.py", line 1056, in open_mfdataset
    datasets = [open_(p, **open_kwargs) for p in paths]
  File "/home/gregoriorandazzo/.local/lib/python3.10/site-packages/xarray/backends/api.py", line 1056, in <listcomp>
    datasets = [open_(p, **open_kwargs) for p in paths]
  File "/home/gregoriorandazzo/.local/lib/python3.10/site-packages/xarray/backends/api.py", line 579, in open_dataset
    ds = _dataset_from_backend_dataset(
  File "/home/gregoriorandazzo/.local/lib/python3.10/site-packages/xarray/backends/api.py", line 372, in _dataset_from_backend_dataset
    ds = _chunk_ds(
  File "/home/gregoriorandazzo/.local/lib/python3.10/site-packages/xarray/backends/api.py", line 337, in _chunk_ds
    variables[name] = _maybe_chunk(
  File "/home/gregoriorandazzo/.local/lib/python3.10/site-packages/xarray/core/dataset.py", line 299, in _maybe_chunk
    chunked_array_type = guess_chunkmanager(
  File "/home/gregoriorandazzo/.local/lib/python3.10/site-packages/xarray/namedarray/parallelcompat.py", line 119, in guess_chunkmanager
    raise TypeError(
TypeError: manager must be a string or instance of ChunkManagerEntrypoint, but received type <class 'xarray.core.daskmanager.DaskManager'>
Location: /home/gregoriorandazzo/Desktop/blender-4.0.2-linux-x64/4.0/scripts/modules/bpy/ops.py:109
Location: /home/gregoriorandazzo/Desktop/blender-4.0.2-linux-x64/4.0/scripts/modules/bpy/ops.py:109

File "/home/gregoriorandazzo/.config/blender/4.0/scripts/addons/blendernc/core/update_ui.py", line 346, in update_file_vars

**Comment by josuemtzmo** [comment]
Hello @g-randazzo,

Unfortunately, due to changes in the API of blender 4.0, BlenderNC is not yet supported in this version of blender. I will recommend you install BlenderNC in blender 3.6. 

I'm currently working to add support of BlenderNC to this version, but I haven't found some workarounds to some of the API changes.

**Comment by g-randazzo** [comment]
Thanks for the quick reply, I'll try 3.6
